# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Artist(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, artist: str=None):
        """
        Artist - a model defined in Swagger

        :param artist: The artist of this Artist.
        :type artist: str
        """
        self.swagger_types = {
            'artist': str
        }

        self.attribute_map = {
            'artist': 'artist'
        }

        self._artist = artist

    @classmethod
    def from_dict(cls, dikt) -> 'Artist':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Artist of this Artist.
        :rtype: Artist
        """
        return deserialize_model(dikt, cls)

    @property
    def artist(self) -> str:
        """
        Gets the artist of this Artist.

        :return: The artist of this Artist.
        :rtype: str
        """
        return self._artist

    @artist.setter
    def artist(self, artist: str):
        """
        Sets the artist of this Artist.

        :param artist: The artist of this Artist.
        :type artist: str
        """

        self._artist = artist

