# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.artist import Artist
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Info(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, title: str=None, artists: List[Artist]=None):
        """
        Info - a model defined in Swagger

        :param title: The title of this Info.
        :type title: str
        :param artists: The artists of this Info.
        :type artists: List[Artist]
        """
        self.swagger_types = {
            'title': str,
            'artists': List[Artist]
        }

        self.attribute_map = {
            'title': 'title',
            'artists': 'artists'
        }

        self._title = title
        self._artists = artists

    @classmethod
    def from_dict(cls, dikt) -> 'Info':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Info of this Info.
        :rtype: Info
        """
        return deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """
        Gets the title of this Info.

        :return: The title of this Info.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """
        Sets the title of this Info.

        :param title: The title of this Info.
        :type title: str
        """

        self._title = title

    @property
    def artists(self) -> List[Artist]:
        """
        Gets the artists of this Info.

        :return: The artists of this Info.
        :rtype: List[Artist]
        """
        return self._artists

    @artists.setter
    def artists(self, artists: List[Artist]):
        """
        Sets the artists of this Info.

        :param artists: The artists of this Info.
        :type artists: List[Artist]
        """

        self._artists = artists

